### ISSUE TITLE
unable to get the desired output

### ISSUE THREAD

**Issue by shaisthajabeen610** [ashstrahle/PowerShellPortal#9]
![image](https://user-images.githubusercontent.com/67311615/185869115-4e91ff0f-89f5-4104-97a2-5b894828ffe0.png)

I am unable to get the desired output. Can you please tell me whats the error

**Comment by ashstrahle** [comment]
Hi @shaisthajabeen610. Can you confirm that the execution policy commands have been executed within package manager shell?

**Comment by shaisthajabeen610** [comment]
Set-ExecutionPolicy Unrestricted -Scope LocalMachine
    Set-ExecutionPolicy Unrestricted -Scope CurrentUser
    Set-ExecutionPolicy Unrestricted -Scope Process
@ashstrahle  are you referring to these commands ?

**Comment by ashstrahle** [comment]
Yes. Without relaxing the Execution Policy you will experience the issue you're having.

**Comment by shaisthajabeen610** [comment]
I have executed the commands but still facing the same issue.
Is it possible for you to attend a quick Teams meeting.

**Comment by ashstrahle** [comment]
Please run those commands within the Package Manager console as per readme. It will have to be another time though I'm afraid, as it's already very late here in Australia.

**Comment by shaisthajabeen610** [comment]
![image](https://user-images.githubusercontent.com/67311615/185932816-660536a5-7a89-4e88-9c40-dac508544680.png)
 hi @ashstrahle I have executed those commands in Package Manager Console but still unable to get the output.
I will be able to connect anytime between 10:00AM [IST] to 5:00PM[IST]

**Comment by shaisthajabeen610** [comment]
![image](https://user-images.githubusercontent.com/67311615/185933462-e0ff0e1d-5984-48fd-a4b9-7ad7db84075c.png)
Do we need to select anything specificallly here in the dropdown @ashstrahle ?

**Comment by ashstrahle** [comment]
That's correct. There's obviously something specific to your environment where the execution policies are not correctly applying. 

I've just created a new Blazor server version of this project, which is far more modernised and simplified. Blazor server natively uses SingalR, which my original project had implemented to achieve realtime results. The Blazor implementation further removes the authentication requirement of this project. Please go to https://github.com/ashstrahle/PowerShellBlazor, and try.

You'll still need to apply the execution policies as per doco so that Windows allows the script to execute.

Let me know how you go.

**Comment by shaisthajabeen610** [comment]
thankyou @ashstrahle will try that.

**Comment by shaisthajabeen610** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/67311615/186133700-cb07f8d6-ffbf-4cb4-a1d7-d704b0c1727b.png)
Environment - Newly build Azure VM and got all required permissions. Added the Set-Execution Policy both in Powershell and VS package manager. Code is running without any errors but not showing output in browser.

**Comment by ashstrahle** [comment]
Ah. so you're running this project in Azure! I've only tested and documented this project for locally hosted Windows and Linux machines. Nevertheless, it's of great value to resolve this in an Azure environment. 

Will research Azure security/policies to see if we can initiate execution of scripts via .Net WebApps, and how we go about achieving  that. Please also contribute your findings.

**Comment by shaisthajabeen610** [comment]
After Changing permissions on the registry, Script is running and getting test results. However, when I am testing with Basic Azure PS commands like Connect-AzAccount and other commands. I am getting unrecognized command. Will this support Azure Powershell? or only windows powershell.. ?

![image](https://user-images.githubusercontent.com/67311615/186139972-4b6e29f6-866a-4d01-9300-4a4ff42659fc.png)

**Comment by ashstrahle** [comment]
Is this of any value? https://azurelessons.com/the-term-get-azuresubscription-is-not-recognized/

**Comment by ashstrahle** [comment]
Closing issue as this repo is being archived.
